version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true

environment:
  BROKER_URL: redis://localhost:6379/0
  matrix:
    - PYTHON: C:\Python38-x64
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python36-x64

install:
  - ps: >
      & "$env:PYTHON\python.exe" -m virtualenv C:\pacifica;
      C:\pacifica\Scripts\activate.ps1;
      python -m pip install --upgrade pip setuptools wheel;
      pip install .;
      pip install -r requirements-dev.txt;

before_test:
  - ps: >
      nuget install redis-64 -excludeversion;
      redis-64\tools\redis-server.exe --service-install;
      redis-64\tools\redis-server.exe --service-start;

build: off

test_script:
  - ps: >
      mkdir C:\tmp; C:\pacifica\Scripts\activate.ps1;
      pre-commit run -a;
      $env:EXAMPLE_CPCONFIG = "$PWD\server.conf";
      pip install .;
      cd tests;
      coverage run --include='*/site-packages/pacifica/example/*' -m pytest -xsv;
      coverage report -m --fail-under=100;
