FROM python:3.6

WORKDIR /usr/src/app
COPY . .
RUN pip install --no-cache-dir .
RUN pip install --no-cache-dir uwsgi pymysql psycopg2
ENV PEEWEE_PROTO mysql
ENV PEEWEE_USER example
ENV PEEWEE_PASS example
ENV PEEWEE_PORT 3306
ENV PEEWEE_ADDR 127.0.0.1
ENV PEEWEE_DATABASE pacifica_example
ENV EXAMPLE_CPCONFIG /usr/src/app/server.conf
EXPOSE 8066
ENTRYPOINT [ "/bin/bash", "/usr/src/app/entrypoint.sh" ]
